### PR TITLE
Fix broken tests. Update Excon version. Clean whitespace

### PR DESCRIPTION
**Pull request by backnol**
Instead of generating images dynamically, I've used a static image in the fixtures. 
Change Excon version locking to `>=` to resolve conflicts easily. 
Remove white spaces.

### CODE REVIEW

**Comment by michelemina** [comment]
which trouble did you face using dynamic images?

**Comment by backnol** [comment]
@michelemina The tests were failing in CI, since it was expecting to create the image in a location that may not exist in the new environment. Using image as fixture that it is will eliminate the need to dynamically create it.

**Comment by backnol** [comment]
@michelemina Thank you for the merge. Can you create a new release so we can point to your repo instead of our fork. Thanks.

**Comment by michelemina** [comment]
@backnol published on rubygems

**Comment by backnol** [comment]
Thanks @michelemina

**Pull request merged**
